services:
  flask_app:
    image: usf-flask-app:latest
    container_name: usf_flask_app_container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:ChangeMe123@mongo:27017/?authSource=admin
    networks:
      - usf-app-net
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: usf_mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=ChangeMe123
    networks:
      - usf-app-net
    volumes:
      - mongo_data:/data/db

  mongo_express:
    image: mongo-express:latest
    container_name: usf_mongo_express_container
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:ChangeMe123@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=AdminUI123
    networks:
      - usf-app-net
    depends_on:
      - mongo

networks:
  usf-app-net:
    driver: bridge

volumes:
  mongo_data: